config/routes.rb
VirtualHumanWrapper::Application.routes.draw do
  resources :lessons
  resources :users do
      resources :lessons
  end
  scope :api do
      get "/lessons/list(.:format)" => "lessons#list"
      get "/lessons(.:format)" => "lessons#index"
      get "/lessons/:id(.:format)" => "lessons#show"
      post "/lessons/complete(.:format)" => "lessons#complete"
  end

  devise_for :users
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  root 'home#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end
  
  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
    
    has_many :lesson_contents
    has_and_belongs_to_many :users

end

app/models/lesson_content.rb
class LessonContent < ActiveRecord::Base
    belongs_to :lesson
end

app/models/lessons_users.rb
class LessonsUsers < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_and_belongs_to_many :lessons

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception

    after_filter :set_csrf_cookie_for_ng

    def set_csrf_cookie_for_ng
        cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
    end

    protected

    def verified_request?
        super || form_authenticity_token == request.headers['X-XSRF-TOKEN']
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_filter :authenticate_user!

    def index
        @lessons = Lesson.all
    end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

    def index
        @lessons = Lesson.all
    end

    def show
        @lesson = Lesson.where(:id => params[:id]).first
        @lesson_contents = @lesson.lesson_contents.order("page").page(params[:page]).per(1)
    end
    
    def update
        @user = current_user
        @lesson = Lesson.where(:id => params[:id]).first
        LessonsUsers.where(:user_id => @user.id, :lesson_id => @lesson.id, :completed => true).first_or_create
        redirect_to root_path
    end

    def list
        @user = current_user
        @list = LessonsUsers.where(:user_id => @user.id)
        render json: @list
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
    def completed?(user, lesson)
        lesson_user = LessonsUsers.where("user_id = ? AND lesson_id =?", user.id, lesson.id).first || false
        if lesson_user
            return lesson_user.completed 
        else
            return false
        end
    end
end

app/views/home/index.html.erb
<div class="row" >
    <% @lessons.each do |lesson| %>
    <div class="col-md-4">
        <div class="widget tile">
            <div class="well">
                <i class="icon-magnet icon-4x pull-left"></i> 
                <h3> <%=lesson.lesson_name%></h3>
                <a href="<%=lesson_path(lesson)%>" class='btn' >Select Lesson</a>
                <% if completed?(current_user, lesson)%>
                    <a href="<%=lesson_path(lesson)%>" class='btn' >Sim Coach</a>
                <% else %>
                    <a href="<%=lesson_path(lesson)%>" class='btn disabled' >Sim Coach</a>
                <% end %>
            </div>
        </div>
    </div>
    <%end%>
</div>

app/views/home/index_angular.html.erb
<div ng-controller="LessonsCtrl">
    <div ng-controller="LessonsContentCtrl">
        <div class="row" >
            <div ng-switch on="lessonObject.display">
                <div class="col-md-4" ng-switch-when="false">
                    <div class="widget tile" ng-repeat="lesson in lessons">
                        <div class="well">
                            <i class="icon-magnet icon-4x pull-left"></i> 
                            <h3 ng-bind="lesson.lesson_name"></h3>
                            <button class='btn' ng-click="getContent(lesson.id); toggle(); lessonObject.name = lesson.lesson_name; lessonObject.lesson_finished=false">Select Lesson</button>
                            <button class='btn' ng-hide="!lessonComplete(lesson.id)" ng-click="toggle(); lessonObject.name = lesson.lesson_name; lessonObject.sim_coach_finished = false">Sim Coach</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-8 col-md-offset-2" ng-switch on="isCurrentPageIndex($index)" ng-hide="lessonObject.lesson_finished" ng-repeat="content in contents | orderObjectBy: 'page'"> 
                <div class="well lesson-window" ng-switch-when="true">
                    <div class="widget lesson-widget">
                        <h3 ng-bind="lessonObject.name"></h3>
                        <p>{{content.content}}</p>
                        <h3>{{content.page}}</h3>
                        </div>
                        <div ng-hide="contents.length -1 == $index" class='btn pull-right nav-button' ng-click="prevPage();">next</div>
                        <div ng-hide="content.page == 1" class='btn pull-left nav-button' ng-click="nextPage();">back</div>
                        <div ng-show="contents.length -1 == $index" class='btn pull-right nav-button' ng-click="completeLesson(content.lesson_id); prevPage()">Finish!</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div ng-controller="simCoachCtrl">
        <div class='col-md-6' ng-switch on="lessonObject.sim_coach_finished">
            <div class="well lesson-window" ng-switch-when="false">
                <h3 ng-bind="lessonObject.name"></h3>
                <button class='btn' ng-click="lessonObject.sim_coach_finished = true; toggle()">finish</button>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html >
<head>
  <title>VirtualHumanWrapper</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="container">
        <div class="widget nav-widget">
            <div class="well" id="nav-well">
                <div class="nav-bar">
                <a class="title pull-left" href="/">Virtual Human Wrapper</a>
                <% if current_user && current_user.admin? %>
                    <%= link_to "Admin", rails_admin_path, :class=>"btn btn-danger pull-right"%>
                <% end %>
                <% if current_user %>
                    <%= link_to "Sign Out", destroy_user_session_path, :method => :delete, :class=>"btn btn-warning pull-right"%>
                    <p class="signed-in pull-right">Signed in as <%=current_user.email%></p>
                <% end %>
            </div>
            </div>
        </div>
        <%= yield %>
       
    </div>
        <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

</body>
</html>

app/views/lessons/show.html.erb
<div class="col-md-8 col-md-offset-2"> 
    <div class="well lesson-window">
        <div class="widget lesson-widget">
            <h3><%=@lesson.lesson_name%></h3>
            <% @lesson_contents.each_with_index do |lesson_content, i| %>
                <p><%= lesson_content.content.html_safe %></p>
                <% if @lesson_contents.last_page?%>
                    <%=button_to "Finish Lesson", user_lesson_path(current_user, @lesson), :method=>:put, :class=>"btn btn-danger pull-right finish-btn"%>
                <%end%>
            <%end%>
        </div>
    <%= paginate @lesson_contents %>
    </div>
</div>